// Generated by gencpp from file legged_robot/walk_msg.msg
// DO NOT EDIT!


#ifndef LEGGED_ROBOT_MESSAGE_WALK_MSG_H
#define LEGGED_ROBOT_MESSAGE_WALK_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace legged_robot
{
template <class ContainerAllocator>
struct walk_msg_
{
  typedef walk_msg_<ContainerAllocator> Type;

  walk_msg_()
    : heading(0)
    , speed(0)
    , time(0)  {
    }
  walk_msg_(const ContainerAllocator& _alloc)
    : heading(0)
    , speed(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef int32_t _heading_type;
  _heading_type heading;

   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::legged_robot::walk_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::legged_robot::walk_msg_<ContainerAllocator> const> ConstPtr;

}; // struct walk_msg_

typedef ::legged_robot::walk_msg_<std::allocator<void> > walk_msg;

typedef boost::shared_ptr< ::legged_robot::walk_msg > walk_msgPtr;
typedef boost::shared_ptr< ::legged_robot::walk_msg const> walk_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::legged_robot::walk_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::legged_robot::walk_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::legged_robot::walk_msg_<ContainerAllocator1> & lhs, const ::legged_robot::walk_msg_<ContainerAllocator2> & rhs)
{
  return lhs.heading == rhs.heading &&
    lhs.speed == rhs.speed &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::legged_robot::walk_msg_<ContainerAllocator1> & lhs, const ::legged_robot::walk_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace legged_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::legged_robot::walk_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::legged_robot::walk_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_robot::walk_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_robot::walk_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_robot::walk_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_robot::walk_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::legged_robot::walk_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68f7308a667b38e6bfb90d635c4c4f55";
  }

  static const char* value(const ::legged_robot::walk_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68f7308a667b38e6ULL;
  static const uint64_t static_value2 = 0xbfb90d635c4c4f55ULL;
};

template<class ContainerAllocator>
struct DataType< ::legged_robot::walk_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "legged_robot/walk_msg";
  }

  static const char* value(const ::legged_robot::walk_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::legged_robot::walk_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 heading\n"
"int32 speed\n"
"int32 time\n"
;
  }

  static const char* value(const ::legged_robot::walk_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::legged_robot::walk_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.speed);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct walk_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::legged_robot::walk_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::legged_robot::walk_msg_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<int32_t>::stream(s, indent + "  ", v.heading);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEGGED_ROBOT_MESSAGE_WALK_MSG_H
